#!/bin/sh
# shellcheck disable=SC2154,SC1091,SC1090,SC2039
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck disable=SC2086
source $mountpoint/etc/options_menu/scripts/om_functions
script_init

om_network="$options_menu/network"
om_network_cmds="$om_network/commands"
om_network_scripts="$om_network/scripts"
om_wifi_restore="$om_network/restore"
om_wifi_restore_cmds="$om_wifi_restore/commands"
om_wifi_restore_scripts="$om_wifi_restore/scripts"

usb_backup="/media/data/wifi_backup"
nand_backup="$rootfs/etc/wifi_backup"
wpa_supplicant="/etc/wpa_supplicant"

disable_restore_usb="$om_network_cmds/_RestoreUsb"
disable_restore_nand="$om_network_cmds/_RestoreNand"
enable_restore_usb="$om_network_cmds/c0060_RestoreUsb"
enable_restore_nand="$om_network_cmds/c0050_RestoreNand"

backup_path="/media/data/wifi_backup"
backup_dest="usb"
