#!/bin/sh
# shellcheck disable=SC2154,SC1091,SC2034,SC2068,SC2039,SC3051,SC3046,SC3043
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck source=/dev/null
source /etc/preinit
script_init

# PATHS
nand_path="$rootfs/usr/share"
share_path="$mountpoint/usr/share"
ui_path="$share_path/ui"
cloverui_path="$share_path/clover-ui/"
string_path="resources/strings"
root_bin="$rootfs/bin"
usb_path="$mountpoint/media/$modname"
font_dir="$usb_path/fonts"
mod_state_path="$mountpoint$profilepath/$modname"
[ ! -d "$font_dir" ] && font_dir="$nand_path/fonts"


system="$sftype"
s_type="$system"
core="$sftype"
case "$sftype" in
hvcj)
  system="shonen"
  s_type="$system"
  system_string="$ui_path/hvc/$string_path"
  core="nes"
  ;;
nes)
  if [ "$sfregion" = "jpn" ]; then
    system="hvc"
    s_type="$system"
    system_string="$cloverui_path/$string_path"
  fi
  ;;
snes)
  system_string="$ui_path/$sftype-$sfregion/$string_path"
  if [ "$sfregion" = "jpn" ]; then
    system="shvc"
    system_string="$ui_path/$system/$string_path"
  fi
  ;;
esac

# OM PATHS
options_menu="$mountpoint/etc/options_menu"
om_commands="$options_menu/commands"
om_scripts="$options_menu/scripts"
om_images="$options_menu/images"

# FUNCTIONS
game_storage="$(findGameStorage)"

rename() {
  [ -f "$1" ] && mv "$1" "$2"
}

translate() {
  local key="$1"
  local lang_code="en-US"
  local lang_dir
  local value=""
  [ -f "$options_menu/language.cfg" ] && lang_code="$(cat "$options_menu/language.cfg")"
  [ -z "$lang_code" ] && lang_code="en-US"

  for lang_dir in "$options_menu/language" "$options_menu"/*/lang; do
    [ -z "$value" ] && [ -f "$lang_dir/$lang_code.lang" ] && value="$(grep "^${key}=" "$lang_dir/$lang_code.lang" 2>/dev/null | tail -1 | cut -d= -f2-)"
    [ -z "$value" ] && [ -f "$lang_dir/en-US.lang" ] && value="$(grep "^${key}=" "$lang_dir/en-US.lang" 2>/dev/null | tail -1 | cut -d= -f2-)"
  done
  [ -z "$value" ] && value="$key"
  echo "$value"
}

remove() {
  local target
  for target in "$@"; do
    [ -f "$target" ] || [ -d "$target" ] && rm -rf "$target"
  done
}

link() {
  [ -f "$1" ] && ln -sf "$1" "$2"
}

copier() {
  [ -f "$1" ] && cp -r "$1" "$2"
}

create() {
  [ ! -f "$1" ] && touch "$1"
}

enableCmds() {
  local cmd_name
  for cmd_name in "$@"; do
    eval "rename \"\$disable_$cmd_name\" \"\$enable_$cmd_name\""
  done
}

disableCmds() {
  local cmd_name
  for cmd_name in "$@"; do
    eval "rename \"\$enable_$cmd_name\" \"\$disable_$cmd_name\""
  done
}

# two providers, so one being down or blocked isn't read as offline
hasInternet() {
  local host
  ip route 2>/dev/null | grep -q '^default' || return 1
  for host in connectivitycheck.gstatic.com cloudflare.com; do
    nc -z -w 3 "$host" 443 >/dev/null 2>&1 && return 0
  done
  return 1
}

netChecker() {
  if hasInternet; then
    translate NO_PKG_ERR
  else
    translate NO_NET_ERR
  fi
}

toggleDownloads() {
  if hasInternet; then
    enableCmds "downloads"
  else
    disableCmds "downloads"
  fi
}

overlayFS() {
  [ -d "$1" ] && mount -t overlayfs -o lowerdir="$2",upperdir="$1" overlayfs "$2"
}
