#!/bin/sh
# shellcheck disable=SC2154,SC1091,SC1090,SC2039
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck disable=SC2086
source $mountpoint/etc/options_menu/retroarch/scripts/ra_vars
script_init

omRetroarchCmds="$optionsMenu/retroarch/commands"
omRetroarchScripts="$optionsMenu/retroarch/scripts"
disableToggleLoadScreens="$omRetroarchCmds/_ToggleLoadScreens"
enableToggleLoadScreens="$omRetroarchCmds/c0090_ToggleLoadScreens"

# retroarch-clover-child (Ozone builds) dropped the loading-screen swap entirely -
# nothing left for this option to toggle, so hide it instead of failing when picked
enable_cmds "ToggleLoadScreens"
[ ! -f "$rootfs/share/retroarch/assets/RAloading-min.png" ] && disable_cmds "ToggleLoadScreens"

usleep 50000 && $optionsMenu/options --commandPath $omRetroarchCmds/ --scriptPath $omRetroarchScripts --title "RETROARCH_OPTIONS" &
