#!/bin/sh
#  Copyright (C) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Removes the Mega Drive Mini / original-size covers hakchi syncs into every
# game folder; the NES/SNES Mini home menu only reads <code>.png and _small.png.

clean() {
  source /etc/preinit
  script_init

  gStorage="$(findGameStorage)"
  [ -d "$gStorage" ] || return 0
  find "$gStorage" -type f \( -name "*_mdmini.png" -o -name "*_original.png" \) -exec rm -f {} +
}

case "$1" in
start)
	clean &
;;
stop|restart)
;;
*)
	echo "CleanExtraCovers: Please use start."
	exit 1
;;
esac
