name: Build

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:

jobs:
  hmod:
    uses: DefKorns/hmod-build/.github/workflows/hmod.yml@master
    with:
      release-name: Options Menu
      docker: true
      # the compat build relinks with its own rpath and adds a private libstdc++
      make: |
        hmod
        hmod FIX_LIBSTDCXX=1
    secrets: inherit
    permissions:
      contents: write
